POST http://localhost:9000/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "email": "user1@email.com"
}
###

GET http://localhost:9000/api/v1/awards?types=vouchers,products,giftcard&per_page=10&current_page=1&poin=10000 HTTP/1.1
content-type: application/json
###